name: Deploy

on:
  workflow_run:
    workflows: [Release, Leaked Secrets Scan]
    types: [completed]

permissions:
  contents: write
  packages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      # temporary pause this check until spacelift fixes their bug
    if: ${{ github.event.workflow_run.conclusion == 'Xsuccess' }}
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Notify Spacelift of release or secret scan completion (success)
        env:
          SPACELIFT_API_KEY_ENDPOINT: https://trufflesec.app.spacelift.io
          SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
          SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
        run: spacectl run-external-dependency mark-completed --id "${GITHUB_SHA}-release-or-scan" --status finished

  on-failure:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      # TODO: disable/renable spacelift push policy
      # temporary pause this check until spacelift fixes their bug
    if: ${{ github.event.workflow_run.conclusion == 'Xfailure' }}
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Notify Spacelift of release or secret scan completion (failed)
        env:
          SPACELIFT_API_KEY_ENDPOINT: https://trufflesec.app.spacelift.io
          SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
          SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
        run: spacectl run-external-dependency mark-completed --id "${GITHUB_SHA}-release-or-scan" --status failed
